### ISSUE TITLE
Error when in the lambda triggered by the CloudWatch events

### ISSUE THREAD

**Issue by fabiodouek** [Fullscreen/ecs-slack-notifications#9]
I can see the lambda function being triggered, but all of them fails withe following error:

Looking for recent event with same ID...
Saving new event - ID arn:aws:ecs:eu-west-1:xxxxxxxxxx:container-instance/yyyyyyyyyyyy
'startedBy': KeyError
Traceback (most recent call last):
File "/var/task/main.py", line 118, in lambda_handler
update_task_digest(event)
File "/var/task/main.py", line 130, in update_task_digest
event_id = event_detail['startedBy']
KeyError: 'startedBy'

**Comment by boroivanov** [comment]
@fabiodouek can you post one of the CW events triggering the lambda function. You can find it the CW logs for the lambda. Thanks

**Comment by fabiodouek** [comment]
Hi @boroivanov , thanks for the quick response.

Please find following one of the events:

```{
    "account": "xxxxxxxxxx",
    "region": "eu-west-1",
    "detail": {
        "status": "ACTIVE",
        "registeredAt": "2019-01-28T08:01:39.505Z",
        "registeredResources": [
            {
                "type": "INTEGER",
                "name": "CPU",
                "integerValue": 2048
            },
            {
                "type": "INTEGER",
                "name": "MEMORY",
                "integerValue": 3887
            },
            {
                "stringSetValue": [
                    "22",
                    "2376",
                    "2375",
                    "51678",
                    "51679"
                ],
                "type": "STRINGSET",
                "name": "PORTS"
            },
            {
                "stringSetValue": [],
                "type": "STRINGSET",
                "name": "PORTS_UDP"
            }
        ],
        "ec2InstanceId": "i-xxxxxxxxx",
        "agentConnected": true,
        "containerInstanceArn": "arn:aws:ecs:eu-west-1:xxxxxxxx:container-instance/xxxxxxxxxxxxxxxx",
        "pendingTasksCount": 0,
        "remainingResources": [
            {
                "type": "INTEGER",
                "name": "CPU",
                "integerValue": 1536
            },
            {
                "type": "INTEGER",
                "name": "MEMORY",
                "integerValue": 3375
            },
            {
                "stringSetValue": [
                    "22",
                    "2376",
                    "2375",
                    "51678",
                    "51679"
                ],
                "type": "STRINGSET",
                "name": "PORTS"
            },
            {
                "stringSetValue": [],
                "type": "STRINGSET",
                "name": "PORTS_UDP"
            }
        ],
        "version": 4898,
        "clusterArn": "arn:aws:ecs:eu-west-1:xxxxxxxxxx:cluster/test-backend",
        "updatedAt": "2019-02-13T15:27:06.802Z",
        "attributes": [
            {
                "name": "com.amazonaws.ecs.capability.logging-driver.syslog"
            },
            {
                "name": "ecs.ami-id",
                "value": "ami-xxxxxxxxxxx"
            },
            {
                "name": "com.amazonaws.ecs.capability.logging-driver.none"
            },
            {
                "name": "com.amazonaws.ecs.capability.logging-driver.json-file"
            },
            {
                "name": "ecs.vpc-id",
                "value": "vpc-xxxxxxxxxxx"
            },
            {
                "name": "ecs.capability.execution-role-awslogs"
            },
            {
                "name": "com.amazonaws.ecs.capability.docker-remote-api.1.17"
            },
            {
                "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
            },
            {
                "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
            },
            {
                "name": "ecs.capability.docker-plugin.local"
            },
            {
                "name": "ecs.capability.task-eni"
            },
            {
                "name": "ecs.capability.task-cpu-mem-limit"
            },
            {
                "name": "com.amazonaws.ecs.capability.docker-remote-api.1.30"
            },
            {
                "name": "ecs.capability.execution-role-ecr-pull"
            },
            {
                "name": "ecs.capability.container-health-check"
            },
            {
                "name": "ecs.subnet-id",
                "value": "subnet-xxxxxxxxxxx"
            },
            {
                "name": "ecs.availability-zone",
                "value": "eu-west-1b"
            },
            {
                "name": "ecs.instance-type",
                "value": "t3.medium"
            },
            {
                "name": "com.amazonaws.ecs.capability.task-iam-role-network-host"
            },
            {
                "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
            },
            {
                "name": "com.amazonaws.ecs.capability.docker-remote-api.1.24"
            },
            {
                "name": "com.amazonaws.ecs.capability.docker-remote-api.1.25"
            },
            {
                "name": "com.amazonaws.ecs.capability.docker-remote-api.1.26"
            },
            {
                "name": "com.amazonaws.ecs.capability.docker-remote-api.1.27"
            },
            {
                "name": "com.amazonaws.ecs.capability.privileged-container"
            },
            {
                "name": "com.amazonaws.ecs.capability.docker-remote-api.1.28"
            },
            {
                "name": "com.amazonaws.ecs.capability.docker-remote-api.1.29"
            },
            {
                "name": "ecs.cpu-architecture",
                "value": "x86_64"
            },
            {
                "name": "ecs.capability.cni-plugin-version",
                "value": "93f43776-2018.10.0"
            },
            {
                "name": "com.amazonaws.ecs.capability.ecr-auth"
            },
            {
                "name": "com.amazonaws.ecs.capability.docker-remote-api.1.20"
            },
            {
                "name": "ecs.os-type",
                "value": "linux"
            },
            {
                "name": "com.amazonaws.ecs.capability.docker-remote-api.1.21"
            },
            {
                "name": "com.amazonaws.ecs.capability.docker-remote-api.1.22"
            },
            {
                "name": "com.amazonaws.ecs.capability.task-iam-role"
            },
            {
                "name": "com.amazonaws.ecs.capability.docker-remote-api.1.23"
            },
            {
                "name": "ecs.capability.private-registry-authentication.secretsmanager"
            }
        ],
        "versionInfo": {
            "agentVersion": "1.21.0",
            "agentHash": "3d368554",
            "dockerVersion": "DockerVersion: 18.06.1-ce"
        },
        "runningTasksCount": 1
    },
    "detail-type": "ECS Container Instance State Change",
    "source": "aws.ecs",
    "version": "0",
    "time": "2019-02-13T15:27:06Z",
    "id": "9716db9f-47cc-1a84-cb86-xxxxxxxxx",
    "resources": [
        "arn:aws:ecs:eu-west-1:xxxxxxxxxx:container-instance/xxxxxxxxxxxx"
    ]
}
```

**Comment by boroivanov** [comment]
@fabiodouek the bug was fixed. Please pull the latest changes from master and `sls deploy`. Feel free to re-open this ticket if you still get errors.

**Comment by fabiodouek** [comment]
Hi @boroivanov , thanks for that. I can see now records being created in DynamoDB, but it's failing at a further stage:

'message': KeyError
Traceback (most recent call last):
File "/var/task/main.py", line 120, in lambda_handler
update_task_digest(event)
File "/var/task/main.py", line 185, in update_task_digest
ts = post_update_to_slack(event, item)
File "/var/task/main.py", line 277, in post_update_to_slack
ts = res['message']['ts']
KeyError: 'message'

Payload:
```{
    "account": "xxxxxx",
    "region": "eu-west-1",
    "detail": {
        "launchType": "EC2",
        "attachments": [],
        "clusterArn": "arn:aws:ecs:eu-west-1:xxxx:cluster/app-ecs",
        "updatedAt": "2019-02-18T23:38:24.151Z",
        "desiredStatus": "RUNNING",
        "createdAt": "2019-02-18T23:38:21.804Z",
        "taskArn": "arn:aws:ecs:eu-west-1:xxxx:task/xxxxxxx-406f-4e7b-8e5e-5faba373132c",
        "group": "service:app-Service-xxxxxxx",
        "containerInstanceArn": "arn:aws:ecs:eu-west-1:xxxxxx:container-instance/xxxxxx-f45c-40c6-9ab2-71d3a44ab913",
        "pullStartedAt": "2019-02-18T23:38:22.151Z",
        "version": 2,
        "memory": "1024",
        "connectivityAt": "2019-02-18T23:38:21.804Z",
        "startedAt": "2019-02-18T23:38:24.151Z",
        "taskDefinitionArn": "arn:aws:ecs:eu-west-1:xxxxxxx:task-definition/app-ecs-service:5",
        "containers": [
            {
                "memoryReservation": "1024",
                "containerArn": "arn:aws:ecs:eu-west-1:xxxxx:container/xxxx-d7b8-49e7-a932-b19544406af6",
                "taskArn": "arn:aws:ecs:eu-west-1:xxxxx:task/xxxxx-406f-4e7b-8e5e-5faba373132c",
                "name": "app-ecs-service",
                "networkBindings": [
                    {
                        "protocol": "tcp",
                        "bindIP": "0.0.0.0",
                        "containerPort": 80,
                        "hostPort": 32770
                    }
                ],
                "lastStatus": "RUNNING",
                "memory": "1024",
                "cpu": "1024",
                "networkInterfaces": []
            }
        ],
        "lastStatus": "RUNNING",
        "connectivity": "CONNECTED",
        "overrides": {
            "containerOverrides": [
                {
                    "name": "app-ecs-service"
                }
            ]
        },
        "pullStoppedAt": "2019-02-18T23:38:23.151Z",
        "cpu": "1024",
        "startedBy": "ecs-svc/xxxxxxxxx"
    },
    "detail-type": "ECS Task State Change",
    "source": "aws.ecs",
    "version": "0",
    "time": "2019-02-18T23:38:24Z",
    "id": "xxxxxx-4584-e945-c25e-7c6a9702a0f0",
    "resources": [
        "arn:aws:ecs:eu-west-1:xxxxxx:task/xxxx-406f-4e7b-8e5e-5faba373132c"
    ]
}```

**Comment by boroivanov** [comment]
@fabiodouek I pushed a small change. Please redeploy and post me the error message after `Error: Cannot get slack timestamp. Slack response:`.

I'm assuming something is either wrong with the slack token or the app permissions. Make sure you have granted:
- channels:read
- chat:write:bot

Also, double-check the values in your `.env.yml` - see https://github.com/Fullscreen/ecs-slack-notifications#installation Step 4.

**Comment by fabiodouek** [comment]
Hi @boroivanov ,

The error is: channel_not_found. I was trying to send to a private slack channel. When I changed to send to a public slack channel, it worked.
So I guess sending to private channels is not supported? I tried to add additional permissions, but with no luck.

**Comment by boroivanov** [comment]
Good catch. According to [chat.postMessage](https://api.slack.com/methods/chat.postMessage) posting to private channels is supported. However, we'll need to give the app access to list the private channel and also mod the code to support.

It seems your original issue is resolved now. Feel free to create a new issue if you need the feature for posting to private channels.
